### PR TITLE
Fix #72: Support more html syntax

### LINKED ISSUE #72: Support full HTML syntax by migrating old code
Is there any reason why some attributes like `placeholder` are commented: https://github.com/propensive/rapture/blob/dev/html/shared/src/main/scala/syntax.scala#L453  ?

### PR DESCRIPTION
**Pull request by srenault**
The only thing to notice here is I had to rename `object data` to `object Data` because of a name conflict with `data` attribute. Feel free to propose me another solution.

### CODE REVIEW

**Comment by propensive** [comment]
Looks like a weird failure downloading a JAR, just on Scala 2.11... I wonder if it's a problem with Travis?

**Comment by propensive** [comment]
Other than that, this looks fantastic! Thank you!

**Comment by propensive** [comment]
It built fine locally with Scala 2.11, so I'm going to merge it. :)

**Comment by propensive** [comment]
I'm going to try to get #42 fixed in time for the next release too. I think this, in combination with your PR, will make the HTML module a lot more useful!

**Comment by srenault** [comment]
Cool! I'm glad to contribute to a project I use.

**Pull request merged**
